# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('5', 'Главный редактор'), ('4', 'Секретарь'), ('3', 'Начальник полосы')], max_length=255, verbose_name='Роль')),
                ('rubric', models.ManyToManyField(to='number.Rubric', verbose_name='Права на полосы')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователи',
            },
        ),
    ]
