# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='auth',
            field=models.NullBooleanField(default=False, verbose_name='Принудительный выход'),
        ),
    ]
