# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170131_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('5', 'Главный редактор'), ('4', 'Секретарь'), ('3', 'Начальник полосы'), ('2', 'Журналист')], max_length=255, verbose_name='Роль'),
        ),
    ]
