# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('width', models.IntegerField(verbose_name='Ширина, колонок')),
                ('height', models.IntegerField(verbose_name='Высота, модулей')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('show_in_basket', models.BooleanField(default=True, verbose_name='Показывать на сайте?')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Корзина блоков',
            },
        ),
    ]
