# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alias_dep',
            field=models.CharField(default=1, max_length=255, verbose_name='Алиас отдела'),
            preserve_default=False,
        ),
    ]
