# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_task_alias_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
