# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_auto_20161216_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='count_chars',
            field=models.IntegerField(default=100, verbose_name='Количество символов'),
            preserve_default=False,
        ),
    ]
