# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_task_count_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=111, max_length=255, verbose_name='Создатель имя'),
            preserve_default=False,
        ),
    ]
