# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус заявки'),
        ),
    ]
