# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_auto_20161221_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255, verbose_name='Юзер')),
                ('bitrix_uid', models.CharField(max_length=255, verbose_name='id битрикса')),
            ],
        ),
    ]
