# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrix',
            name='bitrix_uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='id битрикса'),
        ),
        migrations.AlterField(
            model_name='bitrix',
            name='creator',
            field=models.CharField(max_length=255, unique=True, verbose_name='Юзер'),
        ),
    ]
