# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_auto_20161221_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='alias',
            field=models.CharField(max_length=255, null=True, verbose_name='Название рубрики алиас'),
        ),
    ]
