# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0005_rubric_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='sortir',
            field=models.IntegerField(null=True, verbose_name='Группировка'),
        ),
    ]
