# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0006_rubric_sortir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название рубрики алиас'),
        ),
    ]
