# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0010_auto_20170309_0236'),
        ('number', '0007_auto_20170303_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя создателя')),
                ('login', models.CharField(max_length=255, verbose_name='Логин создателя')),
                ('owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Владелец')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=255, verbose_name='подзаголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_create', models.DateTimeField(verbose_name='Дата время создания')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('strip', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полоса')),
                ('newspaper', models.BooleanField(verbose_name='Для газеты')),
                ('site', models.BooleanField(verbose_name='Для сайта')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='number.Number')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='claim.Task')),
            ],
        ),
    ]
