# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255, verbose_name='Описание')),
                ('recurrences', recurrence.fields.RecurrenceField(verbose_name='Периодичность')),
                ('order_init', models.IntegerField(verbose_name='Номер страницы')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='number.Rubric', verbose_name='Газетная рубрика')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('role', models.CharField(max_length=255, verbose_name='Роль')),
                ('creator', models.CharField(max_length=255, verbose_name='Создатель')),
                ('recurrences', recurrence.fields.RecurrenceField(verbose_name='Периодичность')),
                ('rubrics', models.TextField(verbose_name='Рубрики')),
            ],
        ),
    ]
